#!/bin/bash
#
#  Copyright (c) 2021, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

# ==============================================================================
# Bash definitions

if [[ -n ${BASH_SOURCE[0]} ]]; then
    script_path="${BASH_SOURCE[0]}"
else
    script_path="$0"
fi
script_dir="$(realpath "$(dirname "${script_path}")")"
repo_dir="$(dirname "${script_dir}")"

# ==============================================================================

install_packages_apt()
{
    echo 'Installing script dependencies...'

    # apt-get update and install dependencies
    sudo apt-get update
    sudo apt-get --no-install-recommends install -y \
        coreutils \
        openjdk-11-jre \
        python3-setuptools \
        python3-pip \
        git-lfs \
        unzip \
        wget
}

install_packages_opkg()
{
    echo 'opkg not supported currently' && false
}

install_packages_rpm()
{
    echo 'rpm not supported currently' && false
}

install_packages_brew()
{
    echo 'Installing script dependencies...'
    brew install \
        coreutils \
        openjdk@11 \
        wget
}

install_packages_source()
{
    echo 'source not supported currently' && false
}

install_packages_pip3()
{
    pip3 install --no-cache-dir --upgrade -r "${repo_dir}/requirements.txt"
}

install_packages()
{
    PM=source
    if command -v apt-get; then
        PM=apt
    elif command -v rpm; then
        PM=rpm
    elif command -v opkg; then
        PM=opkg
    elif command -v brew; then
        PM=brew
    fi
    install_packages_$PM

    if command -v pip3; then
        install_packages_pip3
    fi
}

do_bootstrap_openthread()
{
    echo "Bootstrapping openthread"
    "${repo_dir}"/openthread/script/bootstrap
}

do_bootstrap_silabs()
{
    echo "Bootstrapping silabs"
    "${repo_dir}"/script/bootstrap_silabs
}
main()
{
    if [ $# == 0 ]; then
        install_packages
        do_bootstrap_openthread
        do_bootstrap_silabs
    elif [ "$1" == 'packages' ]; then
        install_packages
    elif [ "$1" == 'openthread' ]; then
        do_bootstrap_openthread
    elif [ "$1" == 'python' ]; then
        install_packages_pip3
    elif [ "$1" == 'silabs' ]; then
        do_bootstrap_silabs
    else
        echo >&2 "Unsupported action: $1. Supported: openthread, silabs"
        # 128 for Invalid arguments
        exit 128
    fi

    echo "Bootstrap completed successfully."
}

main "$@"
