#!/bin/bash

script_dir="$(dirname "$(realpath "$0")")"
repo_dir="$(dirname "$script_dir")"

efr32_get_platforms()
{
    # Gets a list of platforms
    cd $repo_dir/src/
    local platforms=(*efr32*/)
    echo "${platforms[@]%/}"
}

efr32_get_boards()
{
    # Gets a list of boards for a given platform
    #
    # Arg $1 -- EFR32 platform

    local platform="$1"
    local platforms=$(efr32_get_platforms)

    if [[ ! " ${platforms[@]} " =~ " $platform " ]]; then
        echo "ERROR: Invalid platform"
        echo "Valid platforms:   ${platforms[@]}"
        return 1
    fi

    local platform_dir="$repo_dir/src/$platform"

    find $platform_dir -type d -name 'brd*' -exec basename {} \; | sort
}
